# Generated by Django 6.0.4 on 2026-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='brand_name',
            new_name='name',
        ),
    ]
