"""added signup, signin, login, logout, profile, profile-update, password-change

Revision ID: 7e5c75dd5537
Revises: 272e6da85c3f
Create Date: 2026-07-13 12:57:34.870023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5c75dd5537'
down_revision: Union[str, Sequence[str], None] = '272e6da85c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
