# Generated by Django 6.0.4 on 2026-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
